# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ballantine.gemspec
gemspec

gem "rake", "~> 13.0"

group :development, :test do
  gem "pry"
  gem "pry-byebug"
  gem "pry-doc"
end

group :test do
  gem "rspec"
end
