version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.1.2
    steps:
      - checkout
      - run:
          name: Build ruby version
          command: |
            cd ruby
            gem install bundler -v 2.3.20
            gem build ballantine.gemspec
            gem install ballantine
            cd ..
      - run:
          name: Run ballantine
          command: |
            ballantine
            ballantine version
            ballantine init
            ballantine diff ca131ca main
