version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.1.2
    steps:
      - checkout
      - run:
          name: Build ruby version
          command: |
            cd ruby
            gem install bundler
            gem build ballantine.gemspec
            gem install ballantine*.gem
            cd ..
      - run:
          name: Run ballantine
          command: |
            echo "$ ballantine"
            ballantine
            echo "$ ballantine version"
            ballantine version
            echo "$ ballantine init"
            ballantine init
            echo "$ ballantine diff migration/ruby main"
            ballantine diff migration/ruby main
  test:
    docker:
      - image: ruby:3.1.2
    steps:
      - checkout
      - run:
          name: bundle install
          command: |
            cd ruby
            gem install bundler
            bundle config
            bundle check || bundle install
      - run:
          name: rspec
          command: |
            cd ruby
            bundle exec rspec --format progress --format RspecJunitFormatter -o /tmp/test-results/rspec.xml
      - store_test_results:
          path: /tmp/test-results
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
