name: Ruby Gem

on:
  push:
    tags:
      - v0.*
jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.1.x
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x
    - name: Publish to GPR
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
        OWNER: ${{ github.repository_owner }}
    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
    - name: Publish to Homebrew
      run: |
        cd ~
        local sha256=$(curl -sL ${URL}${TAG}.tar.gz | shasum -a 256 | cut -d " " -f 1)
        git clone ${HOMEBREW_URL}
        cd ${HOMEBREW_DIRECTORY}
        git checkout ${HOMEBREW_BRANCH}

        sed -i -e "s#${URL}.*\.tar\.gz#${URL}${TAG}\.tar\.gz#g" ${FORMULA_FILE}
        sed -i -e "s#sha256 \".*\"#sha256 \"${sha256}\"#g" ${FORMULA_FILE}
        cat ${FORMULA_FILE}

        git add ${FORMULA_FILE}
        git commit -m ":arrow_up: Upgrade to ${TAG}"
        git push origin ${HOMEBREW_BRANCH}
      env:
        URL: "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/"
        TAG: "${{ github.ref_name }}"
        HOMEBREW_URL: "https://github.com/oohyun15/homebrew-ballantine.git"
        HOMEBREW_DIRECTORY: "homebrew-ballantine"
        HOMEBREW_BRANCH: "main"
        FORMULA_FILE: "Formula/ballantine.rb"
